### PR TITLE
Remove a useless call: Calling lineVec.dot(qPts[0]) useless

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
I signed it!

**Comment by jcgregorio** [comment]
Thanks for the pull request, follow along on the progress of this change here:

  https://codereview.chromium.org/2234563003

**Comment by jcgregorio** [comment]
Committed: https://skia.googlesource.com/skia/+/0be353487c0971475f9d19f2232d3642ea304b10

 Thanks again!

**Comment by sylvestre** [comment]
Le 11/08/2016 à 13:54, Joe Gregorio a écrit :
> Committed: https://skia.googlesource.com/skia/+/0be353487c0971475f9d19f2232d3642ea304b10
Any reason why the original author is not kept?
Thanks
s

**Comment by jcgregorio** [comment]
We don't directly accept pull requests, so I manually copied your contribution over to our normal submission process. If you are going to be submitting patches to Skia regularly then this is the process to follow:

  https://skia.org/dev/contrib/submit

Following that process will also keep the original author information intact on the git commit.

**Comment by sylvestre** [comment]
Well, _git commit --amend --author_ does the job too...
This is an unexpected way to recognize external contributions (especially as I signed the CLAs).

**Comment by HalCanary** [comment]
Unfortunately, the Reitveld tool we use to manage our repository clobbers both the author and committer fields of the commit (as well as adding its own commit message)

**Comment by sylvestre** [comment]
OK, thanks for taking the time to reply to my rant :)

**Pull request closed without merging**
