### PR TITLE
Add SkSurface::MakeFromMTLTexture

### PR DESCRIPTION
**Pull request by knopp**
Something like this would be required to get partial redraw in flutter working for metal. Related issues:

flutter/flutter#67056
flutter/flutter#33939

### CODE REVIEW

**Comment by liyuqian** [comment]
@knopp : Skia didn't use Github for contribution. Please check https://skia.org/dev/contrib on how to file issues or contribute code to Skia.

**Comment by knopp** [comment]
@liyuqian, I put this here for now, more or less as placeholder, because I can't seem to be able to create any issue in skia issue tracker.

**Comment by jvanverth** [comment]
Please don't submit this. You can use SkSurface::MakeFromBackendRenderTarget or SkSurface::MakeFromBackendTexture to do the same thing.

**Comment by knopp** [comment]
Thanks. I'll look into it.

**Comment by liyuqian** [comment]
@knopp : Skia said that the public should be able to create issues on https://skbug.com. Can you please check if you've logged in with a Google/gmail account?

**Comment by knopp** [comment]
@liyuqian, I wasn't able to submit feature request last week, but I tried submitting a bug report now and it worked. I'm not sure if feature requests are treated differently or the issue got resolved in the meanwhile.

**Pull request closed without merging**
