### PR TITLE
Added `nullptr` check for `src` in cases where `-1` should be returned

### PR DESCRIPTION
**Pull request by ViralTaco**
This prevents undefined behavior to occur in cases where `src` is `nullptr` but `srcLength`/`srcByteLength` isn't zero.

### CODE REVIEW

**Comment by ViralTaco** [comment]
@googlebot I signed it!

**Comment by johnstiles-google** [comment]
ViralTaco, what motivated this change? If the caller is passing a null src but a non-zero length, isn't that a real error in the calling code, akin to trying to memcpy or strcpy from null? It seems that a crash would be more useful than silent failure.

**Comment by ViralTaco** [comment]
> ViralTaco, what motivated this change? If the caller is passing a null src but a non-zero length, isn't that a real error in the calling code, akin to trying to memcpy or strcpy from null? It seems that a crash would be more useful than silent failure.

I couldn't agree more. But in the documentation it says
https://github.com/google/skia/blob/9671d0aa311b73d2231b53d4a812d1114896c1c3/src/utils/SkUTF.h#L70
so I didn't want to change the behavior that was expected. I'm assuming the calling code is checking for `-1` which is what it would theoretically get, except right now undefined behavior is invoked first (See https://godbolt.org/z/TbGjWb1Ef )

**Comment by johnstiles-google** [comment]
I didn't write that doc, but I don't think "if there is an error" is meant to include errors such as passing an invalid input range. You could also pass an already-freed pointer, or a valid pointer but a length that goes off the end, or a pointer overlapping the destination range, etc. Those are "errors" by a strict definition, but we are not going to try and detect these cases to return -1. We'll do the wrong thing and/or crash, and we expect the caller will notice this and it will give them a chance to fix their code. In other words, I would interpret this text as "if we couldn't parse the source as valid UTF8, we'll return -1".

**Comment by ViralTaco** [comment]
> I didn't write that doc, but I don't think "if there is an error" is meant to include errors such as passing an invalid input range. You could also pass an already-freed pointer […]

In which case we can't do anything about it anyway, that's already undefined behavior when the function gets called

> […], or a valid pointer but a length that goes off the end, or a pointer overlapping the destination range, etc. Those are "errors" by a strict definition, but we are not going to try and detect these cases to return -1. We'll do the wrong thing and/or crash, and we expect the caller will notice this and it will give them a chance to fix their code. In other words, I would interpret this text as "if we couldn't parse the source as valid UTF8, we'll return -1".

None of the code in that file throws, and I didn't want to make assumptions. I'm not familiar with this code base I just stumbled upon this in another project that has this library as a dependency. I'm not saying my "fix" is perfect. What it is is valid c++, with well defined behavior. I agree, something more concrete should happen right there, I just don't know what. I understand this is nitpicky, until calling that function removes all the nullptr checks on that pointer in the codebase (cf: https://blog.llvm.org/2011/05/what-every-c-programmer-should-know_14.html )
I welcome any alternative you believe would be more fitting. I'm just not familiar with this project [enough] to come up with one.

Sorry if I offended you. 😕

**Comment by johnstiles-google** [comment]
My apologies, no offense taken whatsoever, but I just want to understand the motivation for the change. As it stands it seems overly defensive.
 
"calling that function removes all the nullptr checks on that pointer in the codebase"—could you please elaborate on this and/or provide a godbolt that demonstrates the issue? I would have expected that passing src=null, srcLength=0 would not cause an issue. Passing src=null, srcLength>0 would be an error, sure, and one that I would expect to crash. But if it's doing something more pernicious, I'd like to see?

**Comment by ViralTaco** [comment]
> "calling that function removes all the nullptr checks on that pointer in the codebase"—could you please elaborate on this and/or provide a godbolt that demonstrates the issue?

The following is a bit of (unproductive) fun: 
[This (real world) vulnerability in the linux kernel](https://lwn.net/Articles/342330/) is [referenced on this page of cppreference.com](https://en.cppreference.com/w/cpp/language/ub) which also links to [this godbolt.org demonstration](https://godbolt.org/z/y4vIi1) and by proxy to this [youtube demonstration of the 0day](https://www.youtube.com/watch?v=UdkpJ13e6Z0)

I wouldn't expect that issue to result in a crash. Currently, (crossing my fingers) it returns -1. It just doesn't have to. 
If I understand what you're saying properly, you're suggestion an overload that would take a `std::nullptr_t` and throw some exception, or maybe even assertion failure? 🤔 That would be pretty neat.

**Comment by johnstiles-google** [comment]
OK, thinking about this some more, pointer arithmetic against a null pointer is UB, so calculating `endSrc` is dicey by the letter of the law; I don't think this actually causes an issue on any platform that Skia supports, but UB is UB. I agree that we shouldn't leave in UB, even if it's harmless today.

Rather than check `src` for null, let's check `srcLength` for zero and immediately return zero in that case. This will solve the UB, but it better preserves the actual behavior of today's code. Returning -1 when src is null is a behavioral change that might affect existing callers. (If the caller passes a null src with a non-zero length, they asked for a crash, let them crash.)

AFAICS this should resolve the concern—what do you think?

**Comment by ViralTaco** [comment]
Well, wait. I was about to make the change but… There is no UB if (and only if) the length is 0 and the pointer is null. 
The UB addressed is about adding anything except 0 to `nullptr` so checking for `srcLength` not being `0` might optimize for speed (I'm not sure, I haven't benchmarked it) but it wouldn't prevent this [increasingly improbable-looking] error to occur. 😕

**Comment by johnstiles-google** [comment]
I did some more reading and it looks like nullptr plus zero is well defined in C++ and is safe. (In C it's considered UB apparently, but C++ defines the operation. This confused me in my last response.)

I don't think there is anything to change here.

If a caller passes in a null `src` and a non-zero `srcLength`, they will crash and I am OK with this. They asked us to read data from that pointer, and we did.

If a caller passes in a null `src` and a zero `srcLength`, the behavior seems to be well-defined; no UB is invoked that I can see. We don't read from `src` at all, we don't write anything to `dst`, we don't detect an error, and we return zero. That matches what the docs say we will do.

**Comment by ViralTaco** [comment]
It doesn't crash, though: https://godbolt.org/z/TbGjWb1Ef it returns -1. Because the first function in the while loop returns -1 when src is `nullptr`, the problem with that is that it's after the elusive `nullptr` offset debacle 😕 
Though it might crash. The only thing it won't do is be consistent

**Comment by johnstiles-google** [comment]
Your example demonstrates passing a null source and a non-zero source length. That's a misuse of the API. Callers aren't allowed to do this. It can UB or crash or whatever; the caller specified an invalid input.

**Comment by ViralTaco** [comment]
> Your example demonstrates passing a null source and a non-zero source length. That's a misuse of the API. Callers aren't allowed to do this. It can UB or crash or whatever; the caller specified an invalid input.

So if I "misuse" your API any code I write has undefined behavior. That is good to know. But the header file doesn't say that. Instead it says: https://github.com/google/skia/blob/9671d0aa311b73d2231b53d4a812d1114896c1c3/src/utils/SkUTF.h#L68-L70
If passing `nullptr` alongside a non-zero `srcLength` isn't an error, then 
the function should return a value different than -1. The code does neither of those things. If this condition occurs the code is ill-formed. If you don't fix it, please document it.

**Comment by ViralTaco** [comment]
Since this is intended, and I don't feel like adding documentation would really add anything, I'll close this pull request. 
Thank you for the feedback.

**Comment by ViralTaco** [comment]
Reopened with an alternative solution.

**Comment by johnstiles-google** [comment]
We don't see this as a bug in Skia and don't believe there is a need to make changes here. Please review comments from https://skia-review.googlesource.com/c/skia/+/429297 :

"I agree with John here, if one passes src==nullptr and srcByteLength>0 this should crash as it's a bug at the caller level. Skia acts this way everywhere. Adding zero to nullptr is well defined in C++ (though not in C), so that's all fine."

If you are calling this function directly from your code, you can add a helper function into your project which checks the arguments first, or you can make a local fork of Skia for your project, but we don't think this needs to be upstreamed.

**Comment by ViralTaco** [comment]
> "I agree with John here, if one passes src==nullptr and srcByteLength>0 this should crash as it's a bug at the caller level. Skia acts this way everywhere. Adding zero to nullptr is well defined in C++ (though not in C), so that's all fine."


I agree with that. The problem is that it doesn't [have to] crash. It can return any and all value, or loop forever.
Mea-culpa, when reading the documentation in the header I didn't realize it was a narrow contract.

Also, I'm really sorry about this but since this pr was closed, then reopened, and I didn't actually revert the commit (using web ui) so it opened a new [Gerrit thread (change?)](https://skia-review.googlesource.com/c/skia/+/431816).  😨 
Is it possible to undo that? (I'm still reading the Gerrit docs, this might take a bit…)
In any case, thank you for your patience and the code review.

**Pull request closed without merging**
