### PR TITLE
Remove an useless declaration

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by jcgregorio** [comment]
Thanks, can you submit this as a CL following https://skia.org/dev/contrib/submit ?

**Comment by jcgregorio** [comment]
Following https://skia.org/dev/contrib/submit will make sure you get the credit in the commit. Just wanted to follow up given your public statement here: 

https://twitter.com/SylvestreLedru/status/767391472752689152

**Comment by sylvestre** [comment]
No worries (as you can see with this second PR, I don't mind that much ;)
I was more surprised that your workflow cannot handle this case.

**Comment by jcgregorio** [comment]
But our workflow, this one https://skia.org/dev/contrib/submit, can handle this case.

**Comment by jcgregorio** [comment]
Landed here: https://skia.googlesource.com/skia/+/d0cd2ecf31bb49988bc8a7ff74ee05161c9538de

  Thanks!

**Pull request closed without merging**
